# Substitua pelo nome exato do seu projeto no Shuttle
name = "poem-monitor"

[build]
# Este comando vai listar todos os arquivos e permissões
# na raiz do seu projeto, dentro do ambiente de build do Shuttle.
pre_run_hook = "ls -laR"
